### ISSUE TITLE
Non-stop spinner.

### ISSUE THREAD

**Issue by Arkanine** [joinspontaneous/react-native-loading-spinner-overlay#30]
Sometimes spinner not stops even when visible param receive "true".

**Comment by comountainclimber** [comment]
Im experiencing the exact same issue after upgrading to react-native 34.1... The spinner works as expected most of the time but then fails to turn off under certain circumstances forcing me to exit the app - this appears to only occur on iOS

**Comment by comountainclimber** [comment]
UPDATE: downgrading from react-native 34.1 => .33 solved the issue... it doesnt seem to have anything to do with the `react-native-loading-spinner-overlay`package but rather an update to the ActivityIndicator API which I dont currently have time to track down at the moment

**Comment by sergiocloud** [comment]
same issue here

@comountainclimber isn't good idea downgrading react-native to fix a component bug

**Comment by comountainclimber** [comment]
@sergiocloud I think you would agree its better than having the entire application non functional

**Comment by norikt** [comment]
I suspect that the cause is setting Modal `visible` to false not working...

**Comment by b8ne** [comment]
Hey guys can you post your implementation or steps to reproduce?

**Comment by damir-sirola** [comment]
Might be related to https://github.com/facebook/react-native/issues/10471 ?

**Comment by gsavvid** [comment]
I have the same issue. In random cases but quite often the spinner won't disappear even though I set `visible` to false. I'm using RN 0.33.0. It happens only in iOS whereas it works perfectly fine in Android.

**Comment by b8ne** [comment]
Hey @gsavvid sorry ive been working on my apps backend lately so havent looked at much RN stuff.        Just spent a bit of time looking into it and im tending to agree with @damir-sirola that its related to the iOS issue of not updating UI correctly after state change.  Ill have a play around tomorrow :)

**Comment by gsavvid** [comment]
I also think it's related to Modal. I've implemented a workaround using ActivityIndicator in a View and the problem seem to have been resolved but I don't think it's such a nice solution.

**Comment by mattotodd** [comment]
+1

**Comment by gillesBzk** [comment]
+1

**Comment by prithsharma** [comment]
Any update on this?

**Comment by comountainclimber** [comment]
Any updates on this?? Has anyone found any work arounds currently running rn 39.0 with "react-native-loading-spinner-overlay": "0.4.1" and this issue seemingly occurs completely randomly

**Comment by comountainclimber** [comment]
I can confirm it is definitely related to https://github.com/facebook/react-native/issues/10471

You will only ever see this issue when attempting to combine Alert component with the busy spinner...

**Comment by niftylettuce** [comment]
Same issue here, with `Alert` in combination on later versions of RN, still an issue.

**Comment by niftylettuce** [comment]
Here's a temporary fix everyone (just wrap it with a `setTimeout` of like `100` ms, seems to work for me hahaha)....

```js
this.setState({ spinner: false });
setTimeout(() => {
  Alert.alert('Oops!', err.message);
}, 100);
```

cc @comountainclimber @prithsharma @gillesBzk @mattotodd @gsavvid @b8ne @damir-sirola @norikt @sergiocloud @Arkanine

**Comment by WillSmithInChina** [comment]
finally, I solve this problem as following:
`export default class Loading extends Component{

    constructor(props){
        super(props);
        this.state={
            visible:this.props.visible
        };
        this._show=this._show.bind(this);
        this._hide=this._hide.bind(this);
    }

    render(){
        return(
            <Modal
                animationType={'none'}
                transparent={true}
                visible={this.state.visible}
                onRequestClose={this.props.onDismissLoadingCallback}>
                <View style={{flex:1}}/>
                <View style={{
                    height:80,
                    width:80,
                    alignItems:'center',
                    justifyContent:'center',
                    backgroundColor:'#3434347f',
                    borderRadius:10,alignSelf:'center'}}>
                    <ActivityIndicator
                        animating={true}
                        size={"large"}
                        color={'white'}
                    />
                </View>
                <View style={{flex:1}}/>
            </Modal>
        );
    }


   _show() {
       this.setState({visible:true});
   }


   _hide(){
        this.setState({visible:false});
   }

`

**Comment by luisfuertes** [comment]
I have this issue with rn v0.39.2 

![captura de pantalla 2017-02-20 a las 13 33 22](https://cloud.githubusercontent.com/assets/18212615/23125269/311cec88-f771-11e6-998c-131220fc462a.png)

`Animated: `useNativeDriver` is not supported because the native animated module is missing. Falling back to JS-based animation. To resolve this, add `RCTAnimation` module to this app, or remove `useNativeDriver`.`

**Comment by ithieund** [comment]
Same for me,
Upgrading to 0.4.1 does not help.

**Comment by deepaksisodiya** [comment]
@niftylettuce thanks :)

**Comment by pwoltman** [comment]
Another workaround, assuming you are having the issue of the spinner not dismissing as desired when an Alert has been used on iOS, is to update the visible property when dismissing the Alert itself.

For example:

```
Alert.alert(
  'Alert Title Goes Here',
  'Alert Message Goes Here,
  [
    {text: 'OK', onPress: () => this.setState({spinnerVisible: false})}
  ],
  { cancelable: false }
)

<Spinner visible={this.state.spinnerVisible} textContent={"Processing..."} textStyle={{color: '#FFF'}} />
```

I add the cancelable: false so that Android users can't dismiss without clicking the OK, though this issue doesn't seem to exist on Android so its likely unnecessary.

**Comment by saeropark** [comment]
mine works. if anyone needs.

basically mine will spin until data is fully loaded.

```
class MyList extends React.Component {
  static navigationOptions = {
    header: null,
  }
  constructor(props) {
        super(props);
        
        this.state = {
            visible: true,
            dataSource: new ListView.DataSource({
            rowHasChanged: (row1, row2)=> row1 !== row2
            })
        };
    }

    componentDidMount() {
       // setInterval(() => {
            this.fetchData();
        //}, 3000);
    }

 
    // --- calls Google API ---
    fetchData() {
        fetch(REQUEST_URL)
        .then((response) => response.json())
        .then((responseData) => {
            responseData = this.removeDuplicates(responseData);
            this.setState({
                dataSource: this.state.dataSource.cloneWithRows(responseData),
                visible: false,
            });
        })
        .done();
    }
    render() {
        return (
          <View style={styles.mainContainer}>
          
                  <Spinner visible={this.state.visible} textContent={"Loading..."} textStyle={{color: '#FFF'}} />
           
            <ListView
                dataSource = {this.state.dataSource}
                renderRow = {this.renderBus.bind(this)}
                style = {styles.listView}
            />
            </View>
            
        );
```
    
Dynamic JSON url finish loading, the spinner will stop. hope it helps.

**Comment by tatva-nisarg** [comment]
Any updated on this?

**Comment by niftylettuce** [comment]
Is there a particular version this broke on?  Or react native version?

**Comment by tatva-nisarg** [comment]
I am using 
React native : 0.39.2 
React native Cli : 1.3.0

I am try to debug you file and i found that model was not close while visibility is false any idea about it?

**Comment by aterribili** [comment]
Im using 
React native: `0.43.3`

When the Spinner receives a `true` and after a while a `false`, it doesn't stop.

**Comment by mealbarracin10** [comment]
i am using 
react-native-cli: 2.0.1
react-native: 0.46.1

and don't stop spinner, Any updated on this ?

**Comment by Sonblind** [comment]
This issue still exists. I am not using an alert, and the Activity Indicator spins for ever after the component that rendered it has unmounted. Does anyone have a solution to this problem?

I'm using react-native: `0.48.4`

**Comment by Sonblind** [comment]
I tried building my own, and the issue is that the RN `Modal` component is never dismissed. This happens one out of five times. Any ideas for how to fix this?

**Comment by niftylettuce** [comment]
This solution does not work? @Sonblind @mealbarracin10 @tatva-nisarg 

<https://github.com/joinspontaneous/react-native-loading-spinner-overlay/issues/30#issuecomment-276845098>

**Comment by Sonblind** [comment]
@niftylettuce I am not using an Alert. I am changing the navigator.

**Comment by Sonblind** [comment]
@niftylettuce The issue is that the react component will sometimes unmount before unmounting the modal component inside of this library.

Solution:
---------
Add the loading screen at the root level and control it by a global store vs having multiple loading spinner components inside the children. This ensures that the parent component is always in memory and can unmount the modal component inside the library. 

I'm using mobX, so I achieve this by calling `LoadingScreenStore.setIsVisible(true)` from any component that would need it. I have not see the bug anymore after doing it this way. 👍

**Comment by derakhshanfar** [comment]
same issue for me

**Comment by mrgcohen** [comment]
Does `{ loading <Spinner /> } ` rather than `<Spinner visible={loading} />` work?

**Comment by aouaki** [comment]
It does not change anything on my and @mrgcohen

**Comment by izikandrw** [comment]
still a problem with Alerts

**Comment by MedinaGitHub** [comment]
a solution that worked for me, when I make it visible true and then visible false very quickly it falls, so with a setTimeout in the false it is fixed.

WORK
this.setState({ visible:true })

   setTimeout(() => {

                  this.setState({ visible:false })  

                }, 3000);

NOT WORK
this.setState({ visible:true })
this.setState({ visible:false })

**Comment by vksgautam1** [comment]
same issue

**Comment by yingdongzhang** [comment]
@MedinaGitHub 

this.setState({ visible:true })
this.setState({ visible:false })

won't work because setState is async, there's a callback function you can pass into setState:

`this.setState({ visible: true }, () => { this.setState({ visible: false }) })`

**Comment by coolboiime** [comment]
Just re-confirming here: Putting a delay on the Alert solves the issue. In addition, not sure if it's also related to my problem, hiding the Modal causes a __setState on unmounted component__ error.

**Comment by mbret** [comment]
Using a delay on the alert does not always solves this issue. Most of the time it will but sometimes it will not and you would use another delay value... You can still use a rather long delay to cover most of the case if not every cases. ex: 300ms

**Comment by niftylettuce** [comment]
I'm going to document this solution along with using it in the root in the README of this project shortly.

**Comment by yeomann** [comment]
while this might be a solution but i'm using redux also since states are being managed by redux, it will be a long wrong around to call `alert` and sometimes or i think most of the time. i don't need to show alert as well. i don't know how this is a fix.

**Comment by cristianoccazinsp** [comment]
Do we really need to wrap all our alerts in a timeout in order for this to work properly? Seems like a bad solution.

**Comment by aprilmintacpineda** [comment]
https://github.com/aprilmintacpineda/react-native-spinner-screen-overlay

**Comment by niftylettuce** [comment]
Pull requests to fix bugs are accepted.
