### ISSUE TITLE
Allow ignoring of Android Back button?

### ISSUE THREAD

**Issue by GeoffreyPlitt** [joinspontaneous/react-native-loading-spinner-overlay#45]
We use this spinner and it works great; but we noticed Android users sometimes press the Back Button and this hides. Is there a way to configure it to ignore Android back-button? We don't seem to be able to control this from our code.

**Comment by gsavvid** [comment]
I just opened a new [pull request](https://github.com/niftylettuce/react-native-loading-spinner-overlay/pull/46) for this.

**Comment by niftylettuce** [comment]
See 0.4.4 and the updated Readme docs regarding `cancelable` prop (set to false by default).
