### ISSUE TITLE
is there a way  we can show the  existing screen in the background  and just the spinner on top of it ?

### ISSUE THREAD

**Issue by jpca999** [joinspontaneous/react-native-loading-spinner-overlay#59]
![image](https://user-images.githubusercontent.com/1026325/30880416-8b050bd0-a2d0-11e7-9ef0-307f0134d2bd.png)

Here it keeps the old screen there , it just adds the spinner on the screen 

![img_0666](https://user-images.githubusercontent.com/1026325/30880500-c5342ec6-a2d0-11e7-9d48-b95bab310a0c.PNG)

**Comment by pcooney10** [comment]
@jpca999 if using `react-navigation`, try setting the `cardStyle` `backgroundColor` to `'rgba(0,0,0,0)`. Or in general, make sure your new screen has an opaque background so the previous stack / route can stay visible.
