### ISSUE TITLE
Spinner not hiding when using with alert

### ISSUE THREAD

**Issue by fahadhaq** [joinspontaneous/react-native-loading-spinner-overlay#61]
Hi, Having an issues if I display the spinner and then call my api, when I get back the result from the api I change my state to hide the spinner. The problem is that if I show an alert to display the error the spinner doesnt hid. It just keeps spinning and cant cancel or anything.

Here is my code

```
ValidatePromoCode() {
    if (this.state.email != '') {
      this.setState({
        visible: true,
        spinnerText: 'Validating email address'
      });

      //Make the API call
      StudentApi.SetupBuyOnline(this.state.email, DeviceInfo.getUniqueID(), DeviceInfo.getSystemName())
        .then((responseData) => {
          this.setState({
            visible: false,
            spinnerText: ''
          });

          alert(data);
    }
    else {
      this.props.navigation.navigate('GetRegisteredScreen')
    }
  }
```

Can some one please let me know what I am doing wrong? if i dont have the alert the spinner seems to behave correctly. Thanks in advance

**Comment by Daky** [comment]
I will suggest you try to wrap "alert" with setTimeout().

setTimeout(() => {
        Alert.alert(I18n.t('MESSAGE'),I18n.t('ACCOUNT_OR_PASSWORD_ERROR'))
 }, 100);

**Comment by rupalpatel0008** [comment]
@Daky I have put the setTimeout and its still not working

**Comment by fahadhaq** [comment]
the problem isn't the alert box. The spinner does not stop when I show the alert box. I have tried the above but its not working.
