### ISSUE TITLE
Showing statusbar even it's hidden in navigation

### ISSUE THREAD

**Issue by lasuax** [joinspontaneous/react-native-loading-spinner-overlay#63]
Hi there. I've react-native-navigation installed and my login page's statusBar is hidden for immersive look. When the Spinner shows up (while waiting response from my webservice), the status bar becomes visible with a white background. How can I avoid this happening?

**Comment by Daky** [comment]
Since this spinner use <Modal> to pop up the loading, consider taking a look at the following discussion
https://github.com/facebook/react-native/issues/7474
status bar issue is not fixing yet.

**Comment by husnainafzal86** [comment]
Check solution proposed by @Traviskn on https://github.com/facebook/react-native/issues/7474 Working for me like a charm!

**Comment by lasuax** [comment]
Seems like setting styles.xml as
`<style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen">
      </style>`
fixes it for as @Traviskn have mentiones. Thanks @Daky & @husnainafzal86
