### ISSUE TITLE
spinner loading forever

### ISSUE THREAD

**Issue by ducvu91** [joinspontaneous/react-native-loading-spinner-overlay#68]
hi,
I using device oppo A83 and library
"react-native": "^0.55.4",
"react-native-loading-spinner-overlay": "^0.5.2".
When i use loading spinner  with demo code, it ok with setInterval, but when i use setTimeout, it not working. it not turn off.
It loading forever. I reload app it still there, it still show loading, I can not active on my screen. affter, i set visible : true, and reload app, it load twice loading spinner and override together. then I delete tag spinner, it still loading (like cache). When i shutdown app and start again, it just turn off
![37725190_1628291707298406_2045867977361850368_n](https://user-images.githubusercontent.com/19793530/43254523-c2b36328-90f1-11e8-86c2-42d7413e6fbd.png)
![37782664_1628291510631759_7922130012843540480_n](https://user-images.githubusercontent.com/19793530/43254524-c2e7e56c-90f1-11e8-863e-dd4207c43904.png)

**Comment by KaneNguyen** [comment]
@ducvu91 : how to fix for issue ?
