### ISSUE TITLE
[iOS] Automatic close the alert 

### ISSUE THREAD

**Issue by datvp09** [joinspontaneous/react-native-loading-spinner-overlay#70]
After calling API and set prop visible to false it automatically close the alert Success on iOS. It may related to re-render issue.
Edit: it actually hide the alert, so I can't interact with the screen

code like below:
```
const result = await API...;
if (result.code !== 0) {
       alert('error');
       Logger.error(result);
} else {
       alert('Success');
}

this.setState({
        visible: false
});
```

**Comment by datvp09** [comment]
After researching somewhere and there is a solution, maybe just workaround:

```
setTimeout(() => {
            this.setState({
                visible: false,
            });
            
            setTimeout(() => {
                alert('ABC...');
            }, 10);
}, 400);
```

**Comment by niftylettuce** [comment]
@datvp09 I will be documenting this in README shortly
