### ISSUE TITLE
Stuck in IOS

### ISSUE THREAD

**Issue by vyasishanatc194** [joinspontaneous/react-native-loading-spinner-overlay#72]
When alert and spinner overlay working together,

alter will dismiss but spinner overlay stuck and nothing happened.

**Comment by cedoucette** [comment]
I'm having this exact same issue.

**Comment by zhuang17** [comment]
same issue here.

**Comment by sryze** [comment]
I'm working on a patch for this issue: https://github.com/facebook/react-native/pull/22666, you are welcome to try it out

**Comment by hery** [comment]
Hello! Same issue here, even without using an `Alert` though.
I've made sure to include the `Spinner` only in my top-level screen, but I still occasionally get a sticky spinner.

Something interesting to note is that it doesn't happen in `Debug` and `Release` builds that I build on my device, but it seems to only affect Fabric Crashlytics ad-hoc builds we deploy remotely.

This is super weird. Keeping an eye out for a fix.

**Comment by just4fun** [comment]
Is there any workaround? Currently this issue will make the app frozen, users can only exit the app then open it again.

**Comment by just4fun** [comment]
@zhuang17 - Thanks, it seems like Alert and Modal are running in same event loop then cause the issue? I remembered Modal will not be supported soon in React Native, so for long term, I think the best solution is to replace Modal with something like the modal in react navigation.

**Comment by amireds** [comment]
do we have any fix for this right now

**Comment by hery** [comment]
What if I'm not using an Alert, and only have a spinner in the topmost component? Any idea why I get that sticky spinner sometimes?

**Comment by just4fun** [comment]
My solution for this issue is to replace `Alert(IOS)` with another message library like `react-native-message-bar`, instead of using wired workaround `setTimeout` which may has timing issue.

**Comment by JeffGuKang** [comment]
Make spinner hide after pressing `Alert` buttons.  I think it is the best way on now. 

```js
Alert.alert("!!!", "Error", [
    { text: "OK", onPress: () => this.setState({ spinner: false }) }
]);
```

**Comment by niftylettuce** [comment]
PR accepted.  Please provide a reproducible test case.
