### ISSUE TITLE
Hide Android Navigation Bar

### ISSUE THREAD

**Issue by JanOwiesniak** [joinspontaneous/react-native-loading-spinner-overlay#74]
I'm opening a new screen with [react-navigation](https://reactnavigation.org/) and using this component as a loading indicator. Android shows the system navigation bar at the bottom of the screen. This navigation bar disappears as soon as the spinner is not active anymore. Removing the spinner from my component, fixes this issue so i guess the component is responsible for it in some way.

![screenshot_20190127-142648](https://user-images.githubusercontent.com/213214/51801783-79504380-2242-11e9-9fd7-36b0720b1920.png)

I'm seeing this Android Navigation Bar Behaviour in other components which all seem to have a _Modal_ in common too:

e.g.

- https://github.com/okgrow/react-native-copilot
- https://github.com/rafaelmotta/react-native-scl-alert

---

Is there a way to always deactivate the android navigation bar? I'm already using this code snippets to accomplish hide android system stuff.

**React Code**

```
    StatusBar.setHidden(true);
```

**Android styles.xml**

```
<resources>
    <style name="AppTheme" parent="Theme.ReactNative.AppCompat.Light.NoActionBar.FullScreen">
    </style>
</resources>

```

**Comment by niftylettuce** [comment]
PR accepted.  Please provide a reproducible test case.
