### ISSUE TITLE
Wrong topic / label (response to #79)

### ISSUE THREAD

**Issue by martnst** [joinspontaneous/react-native-loading-spinner-overlay#80]
In repsonse to #79: 

Please understand what a progress-bar is  and act accordingly.

`[********·················· ]`

This module is a "Loading Spinner Overlay". The topic label `progress-bar` is misleading people here. 

 Thanks.

**Comment by niftylettuce** [comment]
No, it is not.  Please do not open another issue like this on the repository or you will be blocked.

A spinner indicates progress, a loading bar is also known as a progress bar, something is happening, it is loading.  The act of loading is an act of progress.
