### ISSUE TITLE
Response to #80

### ISSUE THREAD

**Issue by martnst** [joinspontaneous/react-native-loading-spinner-overlay#81]
Since you keep closing the conversation i have to reopen new issues once again. I would have preferred a single issue to discuss arguments. Anyway, feel free to block everybody who has some contra arguments, if this is your way of handling things. 

--- 

Answer on #80: 

I am sorry, i have to disagree. I a spinner does not indicate progress. It only indicates activity. Hence it is name ActivityIndicator, e.g. in Apple's UIKit. The is no way of telling or guess how much progress in made from a simple spinning view. Nor is it a bar either.

Have a good one.

**Comment by niftylettuce** [comment]
Take your trolling somewhere else.  This is my project.  These are my opinions.    I've reported you to GitHub and blocked you completely.  The time you spent worried about this issue you could actually have made some meaningful contributions to open source.
