### ISSUE TITLE
Support "statusBarTranslucent" by upgrading to latest react native

### ISSUE THREAD

**Issue by hemche** [joinspontaneous/react-native-loading-spinner-overlay#99]
Add `statusBarTranslucent ` prop to `<Modal>` component which is introduced in latest react native. This will fix the below issue with your library.

![Screenshot_1590198965](https://user-images.githubusercontent.com/4380406/82719302-4328a580-9c77-11ea-955e-e41ffb649b1b.png)

**Comment by niftylettuce** [comment]
PR welcome

**Comment by niftylettuce** [comment]
Closing this, but if you want to submit a PR like I said I will review/accept

**Comment by hemche** [comment]
Thanks @niftylettuce PR is up here https://github.com/joinspontaneous/react-native-loading-spinner-overlay/pull/104

**Comment by niftylettuce** [comment]
v2.0.0 released to npm https://github.com/joinspontaneous/react-native-loading-spinner-overlay/releases/tag/v2.0.0
